spring.application.name=orderManagement

# Configuración de la URL de conexión (asegúrate de que la BD 'order_management' exista en tu Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5443/order_management
spring.datasource.username=postgres
spring.datasource.password=tu_contraseña_aqui

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# En la Fase 5 usaremos Flyway, por ahora dejamos que Hibernate cree las tablas automáticamente para avanzar rápido
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas SQL reales que Spring ejecuta tras bambalinas
spring.jpa.show-sql=true